const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('jsdom');const root=path.resolve(__dirname,'..');
const core=require('../roster-core.js');let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
const csv='\uFEFFStudent Id,Grade,First Name,Last Name,Email - Student\r\n00123,10,Test,"O\'Example, Jr.",ignored@example.com\r\n00456,11,Sample,Student,ignored2@example.com\r\n';
test('Matches supplied headers; preserves leading zeros, quoted commas and names; drops email',()=>{const students=core.parseRoster(csv);assert.equal(students[0].id,'00123');assert.equal(students[0].last,"O'Example, Jr.");assert.deepEqual(Object.keys(students[0]),['id','first','last','grade']);});
test('Rejects ambiguous IDs, missing names and malformed CSV',()=>{assert.throws(()=>core.parseRoster(csv+'00123,12,Other,Student,x\n'),/Duplicate/);assert.throws(()=>core.parseRoster('Student Id,First Name,Last Name\n99,,Test'),/name/);assert.throws(()=>core.parseRoster('Student Id,First Name,Last Name\n99,"Unfinished,Test'),/quoted/);assert.throws(()=>core.parseRoster('Name,Email\nTest,test@example.com'),/Required/);});
test('Supports quoted line breaks and optional grade',()=>{const students=core.parseRoster('Student ID#,First Name,Last Name\n001,"Test\nName","Last ""Quoted"""');assert.equal(students[0].grade,'');assert.equal(students[0].last,'Last "Quoted"');});
const html=fs.readFileSync(root+'/index.html','utf8');
function app(saved){const dom=new JSDOM(html,{url:'https://hall.test/',runScripts:'outside-only'});const w=dom.window;w.alert=()=>{};w.confirm=()=>true;if(saved)w.localStorage.setItem('hc.roster.v1',JSON.stringify(saved));for(const p of ['hall-core.js','roster-core.js','roster.js'])w.eval(fs.readFileSync(root+'/'+p,'utf8'));w.eval(html.match(/<script>([\s\S]*?)<\/script>/)[1]);return dom;}
const dom=app({students:core.parseRoster(csv),importedAt:'2026-09-09T00:00:00Z'}),w=dom.window,d=w.document;
test('Saved roster is available after reopening the app',()=>{assert.equal(w.HallRoster.count(),2);assert.equal(w.HallRoster.lookup('00123').first,'Test');assert.equal(w.HallRoster.lookup('123'),null);});
function scan(id){w.dispatchEvent(new w.CustomEvent('hall:id',{detail:id}));}
test('Scan shows name and grade and saves them in no-pass log',()=>{scan('00123');assert.equal(d.getElementById('passStudentName').textContent,"Test O'Example, Jr.");assert.equal(d.getElementById('passStudentGrade').textContent,'Grade 10');d.querySelector('[name=passType][value="No pass"]').checked=true;d.getElementById('passForm').dispatchEvent(new w.Event('submit',{cancelable:true}));const row=JSON.parse(w.localStorage.getItem('hc.scans'))[0];assert.equal(row.student_first,'Test');assert.equal(row.grade,'10');assert.equal(d.getElementById('refFirst').value,'Test');assert.equal(d.getElementById('refGrade').value,'10');});
test('Unknown IDs remain loggable without inventing a name',()=>{d.querySelector('[data-close=referralSheet]').click();scan('99999');assert.equal(d.getElementById('passStudentName').textContent,'Student not found in roster');d.querySelector('[name=passType][value="Office"]').checked=true;d.getElementById('passForm').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(JSON.parse(w.localStorage.getItem('hc.scans'))[1].student_first,'');});
async function importFile(text){const el=d.getElementById('rosterFile');Object.defineProperty(el,'files',{configurable:true,value:[{size:text.length,text:async()=>text}]});el.dispatchEvent(new w.Event('change'));await new Promise(r=>setImmediate(r));}
(async()=>{
  await importFile('Student Id,First Name,Last Name\n1,One,Test\n1,Two,Test');
  test('Failed import keeps previous roster',()=>{assert.equal(w.HallRoster.count(),2);assert.match(d.getElementById('rosterMessage').textContent,/Duplicate/);});
  const realSet=w.Storage.prototype.setItem;w.Storage.prototype.setItem=function(){throw Error('quota');};await importFile('Student Id,First Name,Last Name\n7,New,Student');w.Storage.prototype.setItem=realSet;
  test('Storage failure does not replace existing roster',()=>{assert.equal(w.HallRoster.lookup('00123').first,'Test');assert.match(d.getElementById('rosterMessage').textContent,/could not save/);});
  await importFile('Student Id,First Name,Last Name\n7,<img src=x onerror=alert(1)>,Student');scan('7');
  test('Successful replacement is persistent and names are rendered as text',()=>{assert.equal(w.HallRoster.count(),1);assert.equal(JSON.parse(w.localStorage.getItem('hc.roster.v1')).students.length,1);assert.equal(d.querySelector('#passStudentName img'),null);assert.match(d.getElementById('passStudentName').textContent,/<img/);});
  test('Removing roster preserves saved hallway log names',()=>{d.getElementById('removeRoster').click();assert.equal(w.HallRoster.count(),0);assert.equal(w.localStorage.getItem('hc.roster.v1'),null);assert.equal(JSON.parse(w.localStorage.getItem('hc.scans'))[0].student_first,'Test');});
  dom.window.close();const empty=app();test('No roster gives a clear import instruction',()=>{empty.window.dispatchEvent(new empty.window.CustomEvent('hall:id',{detail:'00123'}));assert.match(empty.window.document.getElementById('passStudentName').textContent,/Import a roster/);});empty.window.close();console.log(count+' roster checks passed.');
})().catch(e=>{console.error(e);process.exitCode=1;dom.window.close();});
